server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id : reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservation/**
        - id: rack-service
          uri: lb://rack-service
          predicates:
            - Path=/rack/**
        - id: receipt-service
          uri: lb://receipt-service
          predicates:
            - Path=/receipt/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**