apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-deployment
spec:
  selector:
    matchLabels:
      app: client-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
        - name: client-service
          image: eliaszngusach/client-service
          ports:
            - containerPort: 8081