apiVersion: apps/v1
kind: Deployment
metadata:
  name: rack-deployment
  labels:
    app: rack-deployment
spec:
  selector:
    matchLabels:
      app: rack-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: rack-deployment
    spec:
      containers:
        - name: rack-service
          image: eliaszngusach/rack-service
          ports:
            - containerPort: 8081