apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-deployment
  labels:
    app: receipt-deployment
spec:
  selector:
    matchLabels:
      app: receipt-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: receipt-deployment
    spec:
      containers:
        - name: receipt-service
          image: eliaszngusach/receipt-service
          ports:
            - containerPort: 8081