apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
  labels:
    app: reservation-deployment
spec:
  selector:
    matchLabels:
      app: reservation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reservation-deployment
    spec:
      containers:
        - name: reservation-service
          image: eliaszngusach/reservation-service
          ports:
            - containerPort: 8081